services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: NyvS77V4pgBe
      MYSQL_DATABASE: session
      MYSQL_USER: adsouza
      MYSQL_PASSWORD: tdb0WFK6t4B7
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: arm64v8/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: NyvS77V4pgBe
    ports:
      - "8080:80"